# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: main.proto for package 'leadster'

require 'grpc'
require_relative 'main_pb'

module Leadster
  module Greeter
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'leadster.Greeter'

      rpc :CreateLead, ::Leadster::LeadRequest, ::Leadster::LeadReply
    end

    Stub = Service.rpc_stub_class
  end
end
